---
sidebar: sidebar 
permalink: task-gcp-enable-data-services.html 
keywords: google buckets, google storage, google cloud storage working environment, google cloud storage buckets 
summary: Después de descubrir los buckets de Google Cloud Storage en BlueXP, podrás utilizar los servicios de datos de NetApp para backup, organización en niveles y sincronización de datos. 
---
= Utilice los servicios de datos de NetApp con buckets de Google Cloud Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de descubrir los buckets de Google Cloud Storage en BlueXP, podrás utilizar los servicios de datos de NetApp para backup, organización en niveles y sincronización de datos.

* Utiliza el backup y la recuperación de datos de *BlueXP* para realizar backups de los datos de tus sistemas ONTAP y Cloud Volumes ONTAP on-premises en el almacenamiento de objetos de Google Cloud.
+
Para comenzar, ve al lienzo y arrastra y suelta un entorno de trabajo ONTAP o Cloud Volumes ONTAP on-premises en tu entorno de trabajo de Google Cloud Storage.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Más información sobre cómo realizar backups de datos de ONTAP en Google Cloud Storage"^].

* Utiliza la organización en niveles *BlueXP* para organizar en niveles los datos inactivos de los clústeres de ONTAP on-premises en el almacenamiento de objetos de Google Cloud.
+
Para comenzar, ve al lienzo y arrastra y suelta un entorno de trabajo de ONTAP on-premises en tu entorno de trabajo de Google Cloud Storage.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-gcp.html["Obtén más información sobre la organización en niveles de los datos de ONTAP en Google Cloud Storage"^].

* Usa *BlueXP copy and sync* para sincronizar datos con o desde los buckets de Google Cloud Storage.
+
Para empezar, vaya al lienzo y arrastre y suelte el entorno de trabajo de origen en el entorno de trabajo de destino. Tu entorno de trabajo de Google Cloud Storage puede ser el origen o el destino.

+
También puedes seleccionar tu entorno de trabajo de Google Cloud Storage y hacer clic en *Copiar y sincronizar* en el panel Servicios para sincronizar datos con o desde los depósitos de Cloud Storage.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Obtén más información sobre el servicio de copia y sincronización de BlueXP"^].


